version: "3.8"
services:
  flask:
    build: .
    container_name: python-flask
    environment:
      - HelloMessage=Hello iac!
    volumes:
      - ./python:/python
    ports: 
      - "8080:8080"
    restart: on-failure
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80"
    depends_on:
        - flask
    restart: on-failure
