---
- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io

- name: Enable docker services
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Change group and permissions for compose
  file:
    path: /usr/local/bin/docker-compose
    owner: ubuntu
    group: ubuntu
